reviews:
  profile: assertive
  request_changes_workflow: true

  high_level_summary: true
  poem: false

  auto_review:
    enabled: true

  review_status:
    enabled: true

chat:
  auto_reply: true
